extends: 'C:\Users\dwhieb\Coding\dev\.eslintrc.yaml'

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
  ecmaVersion: 8
  sourceType: script

env:
  browser: false
  node: true

rules:
  require-jsdoc: off
