language: node_js
node_js: node
before_script:
  - npm i --save jasmine@2.4.1
  - node build/less.js
  - babel public/src -d public/js
  - ./node_modules/karma/bin/karma start
notifications:
  email: false
